Add force failure step to first workflow
Add a step to force failure in the workflow

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -21,3 +21,8 @@ jobs:
 
       - name: Listing the files
         run: ls -la
+
+      - name: Force Failur
+        run: |
+         echo "This step will failure"
+         exit 1
